{
    'name': 'TechBox Clinic Management System',
    'version': '1.0',
    'description': 'Clinic Management System built in Odoo17',
    'summary': 'Clinic Management System built in Odoo17',
    'author': 'Techbox, SoftlinkOptions',
    'license': 'LGPL-3',
    'category': 'Healthcare',
    'depends': [
        'base', 
        'mail', 
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/clinic_department_data.xml',
        'views/clinic_department_views.xml',
        'views/clinic_dashboard_views.xml',
        'views/clinic_reception_views.xml',
        'views/clinic_mch_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'sequence': 1,
    'auto_install': False,
    'application': True,
    'installable': True,
    'sequence': 10,
}